# Configuração do DataSource para PostgreSQL no Docker
spring.datasource.url=jdbc:postgresql://db:5433/guardianshield
spring.datasource.username=shield_user
spring.datasource.password=mysecretpassword
spring.datasource.driverClassName=org.postgresql.Driver

# Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true